# Generated by Django 2.2.4 on 2019-08-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='Middle_Name',
            new_name='Last_Name',
        ),
    ]
