# Generated by Django 2.2.4 on 2019-08-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190804_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
