# Generated by Django 2.2.4 on 2019-08-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190804_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='Addr_line1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='crud',
            name='Addr_line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='crud',
            name='Addr_line3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='crud',
            name='Addr_line4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
