# Generated by Django 2.2.4 on 2019-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20190804_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='Middle_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crud',
            name='First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crud',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
